version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ''
    volumes:
      - ./docker/mysql/volumes/data:/var/lib/mysql
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
    networks:
      - default
  app:
    build:
      context: .
      args:
        - BundlerInstallOption=-j3 --no-deployment
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: development
    volumes:
      - ./:/app:cached
    depends_on:
      - mysql
    # command: sh -c "[ -f tmp/pids/server.pid ] && rm tmp/pids/server.pid; exec rails s"
    networks:
      - default
